#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
# 2006.12.19
# 2007-09-27 changed shell-bang! line from /usr/bin/ruby to /usr/bin/env ruby
# その理由はなんだ？2010-08-06.
# 2011-02-25, /opt/local/bin/ruby1.9
# 2011-08-28, use rvm.

require 'webrick'
include WEBrick

def usage()
  print <<EOF
usage:
  server [--port port] [--root documentroot] [--bind the.bind.add.ress]
EOF
  exit(1)
end

port=2000
root='public'
bind='0.0.0.0'

while (arg=ARGV.shift)
  case arg
  when /--port/
    port=ARGV.shift.to_i
  when /--root/i
    root=ARGV.shift
  when /--bind/i
    bind=ARGV.shift
  else
    usage()
  end
end

s=HTTPServer.new(
                 :Port		=> port,
                 :DocumentRoot 	=> File.join(Dir.pwd, root),
                 :Bind 		=> bind
)
trap("INT") {s.shutdown}
s.start
